apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer  # Use LoadBalancer for exposing externally, or ClusterIP for internal only
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 5000  # The port exposed by the Service
    targetPort: 5000  # The port the Flask app is listening on inside the container
