apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - port: 5000      # Port sur lequel le service écoute
    targetPort: 5000 # Port exposé par le conteneur
    nodePort: 30007  # Port accessible depuis votre machine (facultatif, Kubernetes attribue un port automatiquement si non spécifié)